//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 

namespace Innocellence.WeChat.WebService
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "EmployeeInfoSoap", Namespace = "http://fishflowmobility.grapecity.cn/service")]
    public partial class EmployeeInfo : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private GCSoapHeader gCSoapHeaderValueField;

        private System.Threading.SendOrPostCallback GetEmployeeInfoOperationCompleted;

        private System.Threading.SendOrPostCallback GetEmployeeInfo2OperationCompleted;

        /// <remarks/>
        public EmployeeInfo()
        {
            this.Url = "https://fishflow.jjmc.cn:8443/WeChat_WebService/EmployeeInfo.asmx";
        }

        public GCSoapHeader GCSoapHeaderValue
        {
            get
            {
                return this.gCSoapHeaderValueField;
            }
            set
            {
                this.gCSoapHeaderValueField = value;
            }
        }

        /// <remarks/>
        public event GetEmployeeInfoCompletedEventHandler GetEmployeeInfoCompleted;

        /// <remarks/>
        public event GetEmployeeInfo2CompletedEventHandler GetEmployeeInfo2Completed;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GCSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fishflowmobility.grapecity.cn/service/GetEmployeeInfo", RequestNamespace = "http://fishflowmobility.grapecity.cn/service", ResponseNamespace = "http://fishflowmobility.grapecity.cn/service", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmployeeInfo(int CurrentIndex, int PageSize)
        {
            object[] results = this.Invoke("GetEmployeeInfo", new object[] {
                    CurrentIndex,
                    PageSize});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetEmployeeInfo(int CurrentIndex, int PageSize, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetEmployeeInfo", new object[] {
                    CurrentIndex,
                    PageSize}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetEmployeeInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetEmployeeInfoAsync(int CurrentIndex, int PageSize)
        {
            this.GetEmployeeInfoAsync(CurrentIndex, PageSize, null);
        }

        /// <remarks/>
        public void GetEmployeeInfoAsync(int CurrentIndex, int PageSize, object userState)
        {
            if ((this.GetEmployeeInfoOperationCompleted == null))
            {
                this.GetEmployeeInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmployeeInfoOperationCompleted);
            }
            this.InvokeAsync("GetEmployeeInfo", new object[] {
                    CurrentIndex,
                    PageSize}, this.GetEmployeeInfoOperationCompleted, userState);
        }

        private void OnGetEmployeeInfoOperationCompleted(object arg)
        {
            if ((this.GetEmployeeInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmployeeInfoCompleted(this, new GetEmployeeInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GCSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fishflowmobility.grapecity.cn/service/GetEmployeeInfo2", RequestNamespace = "http://fishflowmobility.grapecity.cn/service", ResponseNamespace = "http://fishflowmobility.grapecity.cn/service", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmployeeInfo2(int CurrentIndex, int PageSize)
        {
            object[] results = this.Invoke("GetEmployeeInfo2", new object[] {
                    CurrentIndex,
                    PageSize});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetEmployeeInfo2(int CurrentIndex, int PageSize, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetEmployeeInfo2", new object[] {
                    CurrentIndex,
                    PageSize}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetEmployeeInfo2(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetEmployeeInfo2Async(int CurrentIndex, int PageSize)
        {
            this.GetEmployeeInfo2Async(CurrentIndex, PageSize, null);
        }

        /// <remarks/>
        public void GetEmployeeInfo2Async(int CurrentIndex, int PageSize, object userState)
        {
            if ((this.GetEmployeeInfo2OperationCompleted == null))
            {
                this.GetEmployeeInfo2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmployeeInfo2OperationCompleted);
            }
            this.InvokeAsync("GetEmployeeInfo2", new object[] {
                    CurrentIndex,
                    PageSize}, this.GetEmployeeInfo2OperationCompleted, userState);
        }

        private void OnGetEmployeeInfo2OperationCompleted(object arg)
        {
            if ((this.GetEmployeeInfo2Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmployeeInfo2Completed(this, new GetEmployeeInfo2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fishflowmobility.grapecity.cn/service")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fishflowmobility.grapecity.cn/service", IsNullable = false)]
    public partial class GCSoapHeader : System.Web.Services.Protocols.SoapHeader
    {

        private string userNameField;

        private string passwordField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetEmployeeInfoCompletedEventHandler(object sender, GetEmployeeInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmployeeInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetEmployeeInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetEmployeeInfo2CompletedEventHandler(object sender, GetEmployeeInfo2CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmployeeInfo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetEmployeeInfo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}