// <autogenerated>
//   This file was generated by T4 code generator ModelCodeScript.tt.
namespace Innocellence.Web.Service.ModelConfigurations.Identity
{
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;


using Infrastructure.Core.Data;
    using Innocellence.Web.Entity;



    /// <summary>
    /// 实体类-数据表映射——Role
    /// </summary> 
    public partial class SysUserConfiguration : EntityConfigurationBase<SysUser, Int32>
    { 
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public SysUserConfiguration()
        {
            SysUserConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void SysUserConfigurationAppend();

        partial void SysUserConfigurationAppend()
        {
           // HasRequired(m => m.Organization).WithMany(n => n.Roles);
            HasMany<SysUserRole>(u => u.Roles).WithRequired().HasForeignKey(ur => ur.UserId);
            HasMany<SysUserClaim>(u => u.Claims).WithRequired().HasForeignKey(uc => uc.UserId);
            HasMany<SysUserLogin>(u => u.Logins).WithRequired().HasForeignKey(ul => ul.UserId);

           
        }
    }

    public partial class SysRoleConfiguration : EntityConfigurationBase<SysRole, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public SysRoleConfiguration()
        {
            SysRoleConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void SysRoleConfigurationAppend();

        partial void SysRoleConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
            HasMany<SysUserRole>(r => r.Users).WithRequired().HasForeignKey(ur => ur.RoleId);
        }
    }

    public partial class SysUserRoleConfiguration : EntityConfigurationBase<SysUserRole, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public SysUserRoleConfiguration()
        {
            SysUserRoleConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void SysUserRoleConfigurationAppend();

        partial void SysUserRoleConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
            HasKey(a => new { a.RoleId,a.UserId });
        }
    }

    public partial class SysUserLoginConfiguration : EntityConfigurationBase<SysUserLogin, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public SysUserLoginConfiguration()
        {
            SysUserLoginConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void SysUserLoginConfigurationAppend();

        partial void SysUserLoginConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
            HasKey(l => new
			{
				l.LoginProvider,
				l.ProviderKey,
				l.UserId
			});
        }
    }

    public partial class SysUserClaimConfiguration : EntityConfigurationBase<SysUserClaim, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public SysUserClaimConfiguration()
        {
            SysUserClaimConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void SysUserClaimConfigurationAppend();

        partial void SysUserClaimConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }
}
